language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gavinong/docker-react -f Dockerfile.dev .

script:
  - docker run gavinong/docker-react npm run test -- --coverage
